### ISSUE TITLE
Manage Task Priorities

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/todo-list-django-project#10]
As **a user** I want to **be able to assign priorities to tasks** so that I can **focus on tasks based on their importance and urgency**
  
### Acceptance Criteria:
  
- [x] When creating or editing a task, I can select a priority level from High, Medium, or Low.
- [x] Tasks should be listed in order of priority on the Todo List page from high to low level.

### Tasks
 
- [x] Modify the TodoItem model to include a priority field that references the Priority model.
- [x]  Update the TodoItemForm to include a dropdown/select field for selecting the priority level (High, Medium, Low).
