### ISSUE TITLE
Private or public tasks

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/todo-list-django-project#11]
As **a user** I want to **manage my tasks by setting them as private or public** so that I can **control the visibility of my tasks**
  
### Acceptance Criteria:
  
- [x] Users can set a task as either private or public at the time of creation.
- [x] Private tasks are only visible to the user who created them.
- [x] Public tasks are visible to all users who have access to the application.

### Tasks
 
- [x] Add a checkbox in the task creation form to set the task as private or public.
- [x]  Display private and public tasks differently in the task list view.
- [x] Update the task model to include a visibility field a boolean.
