### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/todo-list-django-project#2]
As **a user** I want to **log in to my account** so that I can **view and manage my to-do list**
  
### Acceptance Criteria:
  
- [x] The login page should have fields for username and password.
- [x] Upon successful login, the user should be redirected to their to-do list page.
- [x] Users should not be able to access the to-do list without logging in.

### Tasks
 
- [x] Create a login form with Django forms.
- [x] Implement login logic in views.py.
- [x] Use Django's authentication system to handle user sessions.
