### ISSUE TITLE
Add New To-Do Item

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/todo-list-django-project#3]
As **a logged-in user** I want to **create a new to-do item** so that I can **keep track of tasks I need to complete**
  
### Acceptance Criteria:
  
- [x] The to-do list page should have a form for adding new items.
- [x] Users should be able to enter a title and description for the new item.
- [x] Newly added items should be displayed on the to-do list.

### Tasks
 
- [x] Design a form for adding new to-do items.
- [x] Implement logic to save new items to the database.
- [x] Display newly added items on the to-do list page.
