### ISSUE TITLE
Mark To-Do Item as Completed

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/todo-list-django-project#4]
As **a logged-in user** I want to **mark a to-do item as completed** so that I can **track my progress**
  
### Acceptance Criteria:
  
- [x] Each to-do item should have a checkbox or button to mark it as completed.
- [x] Completed items should be visually distinct from incomplete items.
- [x] Completed items should remain on the list but marked as completed.

### Tasks
 
- [x] Add a checkbox or button to each to-do item.
- [x] Implement logic to update the status of an item in the database.
- [x] Style completed items differently using CSS.
