### ISSUE TITLE
Edit To-Do Item Details

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/todo-list-django-project#5]
As **a logged-in user** I want to **edit an existing to-do item** so that I can **update its details**
  
### Acceptance Criteria:
  
- [x] Each to-do item should have an edit button.
- [x] Clicking the edit button should open a form pre-filled with the item's current details.
- [x] Users should be able to modify the title and date of the item.

### Tasks
 
- [x] Add an edit button to each to-do item.
- [x] Create an edit form pre-filled with item details.
- [x] Implement logic to update item details in the database.
