### ISSUE TITLE
Delete To-Do Item

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/todo-list-django-project#6]
As **a logged-in user** I want to **delete a to-do item** so that I can **remove tasks I no longer need to complete**
  
### Acceptance Criteria:
  
- [x] Each to-do item should have a delete button.
- [x] Clicking the delete button should prompt the user for confirmation.
- [x] Upon confirmation, the item should be removed from the list.

### Tasks
 
- [x] Add a delete button to each to-do item.
- [x] Implement logic to handle deletion confirmation. 
- [x] Remove the item from the database upon confirmation.
