### ISSUE TITLE
Categories for To-Do List

### ISSUE THREAD

**Issue by SaraabbasiNZ** [SaraabbasiNZ/todo-list-django-project#9]
As **user** I want to **manage categories for my tasks** so that I can **organize my tasks more effectively**
  
### Acceptance Criteria:
  
- [x] The newly created category should appear in the category list.
- [x] When I save the changes, the updated category name should be reflected in the list.

### Tasks
 
- [x] Create a form in the template for adding new categories.
- [x] Develop the view logic to handle category creation and saving to the database.
- [x] Update the category list view to display newly added categories.
